language: node_js
node_js:
  - "5"

before_script:
  - npm install grunt-cli -g
  - wget https://raw.githubusercontent.com/cyChop/dev-resources/master/sonar/sonar.config.js

script: grunt ci

after_success: |
  if [ $TRAVIS_PULL_REQUEST == false -a $TRAVIS_BRANCH == 'quality' ]; then
    grunt sonarRunner:analysis
  fi
